// <auto-generated />
using System;
using LinkUp.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkUp.Data.Migrations
{
    [DbContext(typeof(LinkUpContext))]
    [Migration("20260604143003_AddUserContactEmail")]
    partial class AddUserContactEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("LinkUp.Core.Entities.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Hobby", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Sport",
                            DisplayName = "Sport & Bewegung",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Arts_and_Culture",
                            DisplayName = "Kunst, Kultur & Kreatives",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Travel",
                            DisplayName = "Reisen",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "Cuisine",
                            DisplayName = "Kochen & Kulinarik",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "Technology",
                            DisplayName = "Technologie & Programmieren",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "Gaming",
                            DisplayName = "Gaming",
                            IsActive = true,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "Social_Activities",
                            DisplayName = "Soziale Aktivitäten & Networking",
                            IsActive = true,
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "albanian",
                            DisplayName = "Albanian",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "amharic",
                            DisplayName = "Amharic",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "arabic",
                            DisplayName = "Arabic",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "bosnian",
                            DisplayName = "Bosnian",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "bulgarian",
                            DisplayName = "Bulgarian",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "chinese",
                            DisplayName = "Chinese",
                            IsActive = true,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "croatian",
                            DisplayName = "Croatian",
                            IsActive = true,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "czech",
                            DisplayName = "Czech",
                            IsActive = true,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Code = "danish",
                            DisplayName = "Danish",
                            IsActive = true,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Code = "dutch",
                            DisplayName = "Dutch",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Code = "english",
                            DisplayName = "English",
                            IsActive = true,
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Code = "finnish",
                            DisplayName = "Finnish",
                            IsActive = true,
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            Code = "french",
                            DisplayName = "French",
                            IsActive = true,
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            Code = "german",
                            DisplayName = "German",
                            IsActive = true,
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            Code = "greek",
                            DisplayName = "Greek",
                            IsActive = true,
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            Code = "hebrew",
                            DisplayName = "Hebrew",
                            IsActive = true,
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            Code = "hindi",
                            DisplayName = "Hindi",
                            IsActive = true,
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 18,
                            Code = "hungarian",
                            DisplayName = "Hungarian",
                            IsActive = true,
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 19,
                            Code = "indonesian",
                            DisplayName = "Indonesian",
                            IsActive = true,
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 20,
                            Code = "italian",
                            DisplayName = "Italian",
                            IsActive = true,
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 21,
                            Code = "japanese",
                            DisplayName = "Japanese",
                            IsActive = true,
                            SortOrder = 21
                        },
                        new
                        {
                            Id = 22,
                            Code = "korean",
                            DisplayName = "Korean",
                            IsActive = true,
                            SortOrder = 22
                        },
                        new
                        {
                            Id = 23,
                            Code = "kurdish",
                            DisplayName = "Kurdish",
                            IsActive = true,
                            SortOrder = 23
                        },
                        new
                        {
                            Id = 24,
                            Code = "malay",
                            DisplayName = "Malay",
                            IsActive = true,
                            SortOrder = 24
                        },
                        new
                        {
                            Id = 25,
                            Code = "norwegian",
                            DisplayName = "Norwegian",
                            IsActive = true,
                            SortOrder = 25
                        },
                        new
                        {
                            Id = 26,
                            Code = "persian",
                            DisplayName = "Persian",
                            IsActive = true,
                            SortOrder = 26
                        },
                        new
                        {
                            Id = 27,
                            Code = "polish",
                            DisplayName = "Polish",
                            IsActive = true,
                            SortOrder = 27
                        },
                        new
                        {
                            Id = 28,
                            Code = "portuguese",
                            DisplayName = "Portuguese",
                            IsActive = true,
                            SortOrder = 28
                        },
                        new
                        {
                            Id = 29,
                            Code = "romanian",
                            DisplayName = "Romanian",
                            IsActive = true,
                            SortOrder = 29
                        },
                        new
                        {
                            Id = 30,
                            Code = "russian",
                            DisplayName = "Russian",
                            IsActive = true,
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 31,
                            Code = "serbian",
                            DisplayName = "Serbian",
                            IsActive = true,
                            SortOrder = 31
                        },
                        new
                        {
                            Id = 32,
                            Code = "slovak",
                            DisplayName = "Slovak",
                            IsActive = true,
                            SortOrder = 32
                        },
                        new
                        {
                            Id = 33,
                            Code = "somali",
                            DisplayName = "Somali",
                            IsActive = true,
                            SortOrder = 33
                        },
                        new
                        {
                            Id = 34,
                            Code = "spanish",
                            DisplayName = "Spanish",
                            IsActive = true,
                            SortOrder = 34
                        },
                        new
                        {
                            Id = 35,
                            Code = "swahili",
                            DisplayName = "Swahili",
                            IsActive = true,
                            SortOrder = 35
                        },
                        new
                        {
                            Id = 36,
                            Code = "swedish",
                            DisplayName = "Swedish",
                            IsActive = true,
                            SortOrder = 36
                        },
                        new
                        {
                            Id = 37,
                            Code = "thai",
                            DisplayName = "Thai",
                            IsActive = true,
                            SortOrder = 37
                        },
                        new
                        {
                            Id = 38,
                            Code = "turkish",
                            DisplayName = "Turkish",
                            IsActive = true,
                            SortOrder = 38
                        },
                        new
                        {
                            Id = 39,
                            Code = "ukrainian",
                            DisplayName = "Ukrainian",
                            IsActive = true,
                            SortOrder = 39
                        },
                        new
                        {
                            Id = 40,
                            Code = "urdu",
                            DisplayName = "Urdu",
                            IsActive = true,
                            SortOrder = 40
                        },
                        new
                        {
                            Id = 41,
                            Code = "vietnamese",
                            DisplayName = "Vietnamese",
                            IsActive = true,
                            SortOrder = 41
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.LearningGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LearningGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Practice_Everyday_Language",
                            DisplayName = "Alltagssprache üben",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Improve_Technical_Language",
                            DisplayName = "Fachsprache verbessern",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Cultural_Understanding",
                            DisplayName = "Kulturelles Verständnis vertiefen",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "Interview_Preparation",
                            DisplayName = "Vorbereitung auf Bewerbung / Vorstellungsgespräch",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "Exam_Preparation",
                            DisplayName = "Prüfungsvorbereitung",
                            IsActive = true,
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.TandemForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TandemForm", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Face_to_Face",
                            DisplayName = "Persönlich",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Online",
                            DisplayName = "Online",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Hybrid",
                            DisplayName = "Hybrid",
                            IsActive = true,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.TandemFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TandemFrequency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Weekly",
                            DisplayName = "Wöchentlich",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Monthly",
                            DisplayName = "Monatlich",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Flexible",
                            DisplayName = "Flexibel / nach Bedarf",
                            IsActive = true,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistinctHobby")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MotherLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TandemFormId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TandemFrequencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetLanguageLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MotherLanguageId");

                    b.HasIndex("TandemFormId");

                    b.HasIndex("TandemFrequencyId");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserFavorite", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "FavoriteUserId");

                    b.HasIndex("FavoriteUserId");

                    b.ToTable("UserFavorites", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserHobby", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HobbyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "HobbyId");

                    b.HasIndex("HobbyId");

                    b.ToTable("UserHobby", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserKnownLanguage", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelRank")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "LanguageId");

                    b.HasIndex("LanguageId", "LevelRank", "UserId");

                    b.ToTable("UserKnownLanguage", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserLearningGoal", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LearningGoalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "LearningGoalId");

                    b.HasIndex("LearningGoalId");

                    b.ToTable("UserLearningGoal", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.User", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.Language", "MotherLanguage")
                        .WithMany()
                        .HasForeignKey("MotherLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.TandemForm", "TandemForm")
                        .WithMany()
                        .HasForeignKey("TandemFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.TandemFrequency", "TandemFrequency")
                        .WithMany()
                        .HasForeignKey("TandemFrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotherLanguage");

                    b.Navigation("TandemForm");

                    b.Navigation("TandemFrequency");

                    b.Navigation("TargetLanguage");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserFavorite", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.User", "FavoriteUser")
                        .WithMany()
                        .HasForeignKey("FavoriteUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavoriteUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserHobby", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.Hobby", "Hobby")
                        .WithMany()
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.User", "User")
                        .WithMany("UserHobbies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserKnownLanguage", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.User", "User")
                        .WithMany("KnownLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserLearningGoal", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.LearningGoal", "LearningGoal")
                        .WithMany()
                        .HasForeignKey("LearningGoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.User", "User")
                        .WithMany("UserLearningGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningGoal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.User", b =>
                {
                    b.Navigation("KnownLanguages");

                    b.Navigation("UserHobbies");

                    b.Navigation("UserLearningGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
