// <auto-generated />
using System;
using LinkUp.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkUp.Data.Migrations
{
    [DbContext(typeof(LinkUpContext))]
    [Migration("20260602155103_CatalogLookupTables")]
    partial class CatalogLookupTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("LinkUp.Core.Entities.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Hobby", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Sport",
                            DisplayName = "Sport & Bewegung",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Arts_and_Culture",
                            DisplayName = "Kunst, Kultur & Kreatives",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Travel",
                            DisplayName = "Reisen",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "Cuisine",
                            DisplayName = "Kochen & Kulinarik",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "Technology",
                            DisplayName = "Technologie & Programmieren",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "Gaming",
                            DisplayName = "Gaming",
                            IsActive = true,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "Social_Activities",
                            DisplayName = "Soziale Aktivitäten & Networking",
                            IsActive = true,
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.LearningGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LearningGoal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Practice_Everyday_Language",
                            DisplayName = "Alltagssprache üben",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Improve_Technical_Language",
                            DisplayName = "Fachsprache verbessern",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Cultural_Understanding",
                            DisplayName = "Kulturelles Verständnis vertiefen",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "Interview_Preparation",
                            DisplayName = "Vorbereitung auf Bewerbung / Vorstellungsgespräch",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "Exam_Preparation",
                            DisplayName = "Prüfungsvorbereitung",
                            IsActive = true,
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.TandemForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TandemForm", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Face_to_Face",
                            DisplayName = "Persönlich",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Online",
                            DisplayName = "Online",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Hybrid",
                            DisplayName = "Hybrid",
                            IsActive = true,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.TandemFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TandemFrequency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Weekly",
                            DisplayName = "Wöchentlich",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Monthly",
                            DisplayName = "Monatlich",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Flexible",
                            DisplayName = "Flexibel / nach Bedarf",
                            IsActive = true,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("LinkUp.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DistinctHobby")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TandemFormId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TandemFrequencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MotherLanguage");

                    b.HasIndex("TandemFormId");

                    b.HasIndex("TandemFrequencyId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserFavorite", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "FavoriteUserId");

                    b.HasIndex("FavoriteUserId");

                    b.ToTable("UserFavorites", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserHobby", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HobbyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "HobbyId");

                    b.HasIndex("HobbyId");

                    b.ToTable("UserHobby", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserKnownLanguage", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelRank")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Language");

                    b.HasIndex("Language", "LevelRank", "UserId");

                    b.ToTable("UserKnownLanguage", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserLearningGoal", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LearningGoalId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "LearningGoalId");

                    b.HasIndex("LearningGoalId");

                    b.ToTable("UserLearningGoal", (string)null);
                });

            modelBuilder.Entity("LinkUp.Core.Entities.User", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.TandemForm", "TandemForm")
                        .WithMany()
                        .HasForeignKey("TandemFormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.TandemFrequency", "TandemFrequency")
                        .WithMany()
                        .HasForeignKey("TandemFrequencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TandemForm");

                    b.Navigation("TandemFrequency");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserFavorite", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.User", "FavoriteUser")
                        .WithMany()
                        .HasForeignKey("FavoriteUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavoriteUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserHobby", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.Hobby", "Hobby")
                        .WithMany()
                        .HasForeignKey("HobbyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.User", "User")
                        .WithMany("UserHobbies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobby");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserKnownLanguage", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.UserLearningGoal", b =>
                {
                    b.HasOne("LinkUp.Core.Entities.LearningGoal", "LearningGoal")
                        .WithMany()
                        .HasForeignKey("LearningGoalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LinkUp.Core.Entities.User", "User")
                        .WithMany("UserLearningGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningGoal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LinkUp.Core.Entities.User", b =>
                {
                    b.Navigation("UserHobbies");

                    b.Navigation("UserLearningGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
